<a href="https://colab.research.google.com/github/champtanapat/ASPWEBAPI/blob/master/AI_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assingment Week2

##Hello World

In [2]:
print("Hello World Test")


Hello World Test


## Function, Conditionals, and Iteration

In [3]:
def HelloWorldXY(x, y):
    if (x < 10):
        print("Hello World, x was < 10")
    elif (x < 20):
        print("Hello World, x was >= 10 but < 20")
    else:
        print("Hello World, x was >= 20")
    return x + y
for i in range(8, 25, 5):  # i=8, 13, 18, 23 (start, stop, step)
    print("--- Now running with i: {}".format(i))
    r = HelloWorldXY(i, i)
    print("Result from HelloWorld: {}".format(r))




--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


## Various kinds of loops starting at 0 to 2


In [4]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
    print(i)

print("Iterate over an actual list.")
for i in [0,1]:
    print(i)

print("While works")
i = 0
while i < 2:
    print(i)
    i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


## Numpy and lists

In [5]:
sea_creatures = ['shark', 'cuttlefish', 'squid', 'mantis shrimp', 'anemone']


sea_creatures[0] = 'shark'
sea_creatures[2] = 'squid'
sea_creatures[4] = 'anemone'

In [6]:
import numpy as np # Make numpy available using np.
# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)
print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))


print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))

print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !

Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2

You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>

Use numpy to create a [3,3] dimension array with random number
[[0.83189808 0.07893345 0.08056985]
 [0.19972942 0.35263588 0.24996572]
 [0.98438649 0.54243935 0.34317171]]

Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2

You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


print("\nDoing $ls on filesystem")
!ls -l
!pwd

In [7]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd


Doing $ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Jul 20 13:28 sample_data
/content


#Exercise

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
fruits = ["apple", "banana", "cherry"]

fruits[0] = "kiwi"
fruits.append("orange")
fruits.insert(1, "lemon")
fruits.remove("banana")
print(fruits)


a = 50
b = 10
c = 20
d = 20
if a != b:
  print("yes")
else:
  print("No")

if a == b:
  print("1")
elif a>b:
  print("2")
else:
  print("3")

if a == b and c == d:
  print("Hello")

if a == b or c == d:
  print("Hello")

for i in range(6):
  print(i)
  if i == 3:
    break



['kiwi', 'lemon', 'cherry', 'orange']
yes
2
Hello
0
1
2
3
